"""add currency as optional field

Revision ID: 0ef0f9077be9
Revises: 
Create Date: 2026-04-24 11:49:34.502931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef0f9077be9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('activities', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('flights', sa.Column('currency', sa.String(length=3), nullable=True))
    op.alter_column('trips', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.drop_column('flights', 'currency')
    op.drop_column('activities', 'currency')
    op.drop_column('accommodations', 'currency')
    # ### end Alembic commands ###
